### ISSUE TITLE
Redirect following = successful connect, broken zap creation

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Zapier#2]
By default [`z.request()` will follow redirects](https://github.com/zapier/zapier-platform/tree/master/packages/cli#http-request-options) which can result in unexpectedly broken account connections, especially on Pro.

Example of bad flow:

```
GET {customdomain}/ghost/api/v2/site/
-> 302
-> GET {admindomain}/ghost/api/v2/site/
-> 👍 ghost site exists and has correct version

GET {customdomain}/ghost/api/v2/config/
-> 302
-> GET {admindomain}/ghost/api/v2/config/
-> 🎉 working "connect"

...some time later...

POST {customdomain}/ghost/api/v2/webhooks/
-> 302
-> GET {admindomain}/ghost/api/v2/webhooks/
-> 💥 broken zap creation
```

We should be able to disable redirect following for all requests, if we do follow redirects we can't guarantee that any POST requests will work.

### To do:
- [ ] close [related issue](https://developer.zapier.com/app/1566/issues/6?from_url=https%3A%2F%2Fdeveloper.zapier.com%2Fapp%2F1566%2Fissues) in Zapier

**Comment by naz** [comment]
The original Zapier issue has been closed and has not come up since a long time, closing it as stale.
