### ISSUE TITLE
Featured Image field is saving Zapier's hydration pointer uri, not uploading image

### ISSUE THREAD

**Issue by hwlmatt** [TryGhost/Zapier#55]
### Expected Behavior
Featured Image field uploads the selected image to Ghost

### Actual Behavior
The Featured Image field is not uploading an image file passed to it, but rather saving the uri reference pointer (the [stashFile like in this example](https://github.com/codebycaleb/zapier-hydration-example/blob/95cf86cbbf207418b0c84ee8367784a78f28da03/hydrators.js#L13) created during a previous step's hydrator (download from external source to zapier). This results in site images being served from Zapier's stashfile url.

### Steps to Reproduce

- Any Trigger
- Get a file from somewhere, say using Google Drives Find File by Name
- Pass the retrieved FILE on to Ghost's Zap and set it as the Featured Image
- Run Zap
- the url of the featured image of the newly created post will be something like: 
    `<img src="https://zapier.com/engine/hydrate/00000000/##################.../"...`

### Possible Cause
**Cause**
~~Line 99 of create_post.js~~
~~[            {key: 'feature_image', required: false},](https://github.com/TryGhost/Zapier/blob/4ecfc0c121a6bc8be7cb2c05f6f23a8841aa8df8/app/creates/create_post.js#L99)~~

~~is missing `type: 'file'~~ 
Ghost's [createPost](https://github.com/TryGhost/Zapier/blob/4ecfc0c121a6bc8be7cb2c05f6f23a8841aa8df8/app/creates/create_post.js#L3) function is not handling dehydration. 

~~So I think~~ this is just passing along that pointer uri as a text string. 

That uri gets saved on the site's end, and loaded on the frontend as an externally hosted image. But that uri is intended to be passed and dehydrated, not as a permanent uri of a file. 
 
### Possible Fix 
[ UPDATE: [see comment below with links to gists](https://github.com/TryGhost/Zapier/issues/55#issuecomment-1000975037). I have uploads working in a clone of this now.] Handling multiple passed files and only uploading uniques, and getting the string back from Ghost api to pass with the rest of the createPost form.

Optional:
Could [add a dehydrateFile method to createPost's res](https://github.com/codebycaleb/zapier-hydration-example/blob/95cf86cbbf207418b0c84ee8367784a78f28da03/creates/uploadFile.js#L21) if you wish to make the Ghost uploaded image available to future Zap steps. Thought this doesn't seem necessary.

~~Sorry I couldn't be more help with a PR or something, I'm not where I can setup anything to test, etc.~~
Happy to do a PR if the gists in my later comment look up to standards.

### Reference docs 
This is an example of an upload hydration/dehydration:
[https://github.com/codebycaleb/zapier-hydration-example/blob/master/creates/uploadFile.js](https://github.com/codebycaleb/zapier-hydration-example/blob/master/creates/uploadFile.js)

Zapier's cli docs on [hydration/dehydration](https://platform.zapier.com/cli_tutorials/hydration)

**Comment by hwlmatt** [comment]
I have a version of this working in a test zap now, but a small caveat:
On the admin-api side of things, the `if (data instanceof FormData) {` checks in [`isValidUpload()`](https://github.com/TryGhost/SDK/blob/b0e19dbf42bfa102c7309626c6d7c3cca984b9fb/packages/admin-api/lib/index.js#L184) and [`getFormData()`](https://github.com/TryGhost/SDK/blob/b0e19dbf42bfa102c7309626c6d7c3cca984b9fb/packages/admin-api/lib/index.js#L198) reject the FormData sent. If I comment those out, the image uploads and the Zap proceeds as intended. 

I don't know if the Validation failure is an error on my end in the creation of FormData, or if the POST process strips some part of that, etc. 

The code that works, (albeit with the above caveat for now), is below. 

Hopefully someone more knowledgable can resolve the FormData validation failure, etc. 
I'm not sure what I have incorrect.

### create_post.js
Just one require and two lines added
```
const {initAdminApi} = require('../lib/utils');
const {uploadFeaturedImage} = require('../lib/upload_featured_image');

const createPost = async (z, {inputData, authData}) => {
        ...
    const authorSlugs = inputData.authors || [];

    const uploadedImage = await uploadFeaturedImage(z, inputData, authData);

    inputData.feature_image = uploadedImage.file;

    inputData.tags = ...
        ...
```

### app/lib/upload_featured_image.js [(gist)](https://gist.github.com/hwlmatt/b6ae1297274208bbd1a893475b8cda09#file-upload_featured_image-js)
```
const FormData = require('form-data');
const axios = require('axios');
const hydrators = require('./hydrators');
const {initAdminApi} = require('../lib/utils');
const contentDisposition = require('content-disposition');

/*
* Utility: Checks buffer and returns mime type onlt if Jpeg or PNG
*/
const isJpgOrPng = async (f) => {
  const hex = f.toString('hex', 0, 4).toUpperCase();
  switch (hex) {
    case '89504E47':
      return 'png'
    case 'FFD8FFE0':
      return 'jpeg'
    default:
      return false
  }
}
/*
* Utility: Quick grab of filename
*/
const filenameFromUrl = (url) => {
  return url.split('#').shift().split('?').shift().split('/').pop();
}
/*
* Utility: filename from Content Disposition
* from: https://github.com/codebycaleb/zapier-hydration-example/blob/95cf86cbbf207418b0c84ee8367784a78f28da03/utils.js#L18
*/
const getFilenameFromContentDisposition = (header) => {
  let filename = '';
  if (!header) {
    return filename;
  }
  try {
    filename = contentDisposition.parse(header).parameters.filename;
  } catch (e) {
    const match = /^.*filename="(.*)".*/.exec(header);
    if (match) {
      filename = match[1];
    }
  }
  return filename;
}

/*
* Retrieval and upload of the file to Ghost
*
*/
const uploadFeaturedImage = async (z, inputData, authData) => {
  // Get image from previous Zap step by its pointer
  const image = await axios({
    url: inputData.feature_image,
    method: 'GET',
    responseType: 'arraybuffer'
  });

  const filename = getFilenameFromContentDisposition(image.headers['content-disposition']);
  // accept only png and jpeg
  const type = await isJpgOrPng(image.data);

  if (!type) {
    //throw here?
    throw new Error("Only JPEG and PNG files allowed for Featured Image");
    return { id: null, file: null }
  }

  const formData = new FormData();
  formData.append('file', image.data, {
    contentType: `image/${type}`,
    name: 'image',
    filename: filename
  });

  const api = initAdminApi(z, authData);

  /**
  *   Veriyfing FormData instanceof before POST
  *   Somethng maybe stripping this in flight?
  *   Leaving this here for inspection later

    let instanceCheck = formData instanceof FormData;
    z.console.log('testing formdata before api call', instanceCheck);
    z.console.log('formData as string', JSON.stringify(formData));
  *
  */
  return api.images.upload(formData).then(res => {

    function convertToGhostUrl(url) {
      url = `__GHOST_URL__/content${url.split('content')[1]}`;
      return url;
    }
    // upload as relative Ghost Url rather than site domain
    let gUrl = convertToGhostUrl(res.url);
    // if res.ref comes back null, get filename from res.url
    let gId = res.ref ||  filenameFromUrl(res.url);
    /*
    * dehydration step was having issues, not required, but will return to it
    * it creates a new pointer for any Zap steps down the chain to reference
    * the file uploaded to the ghost, rather than the one from the previous step
    *
      const filePointer = z.dehydrateFile(hydrators.downloadFile, {
        filename: res.url
        });
      return { id: gId, file: filePointer}
    */
    return { id: gId, file: gUrl }
  });
};

module.exports = {
  uploadFeaturedImage
};```

**Comment by naz** [comment]
Hey @hwlmatt the PR where we could discuss and see the differences would be much appreciated. Some comments on the approach you've taken: 
- the upload_images.js  file looks like something that should be done through the Admin SDK rather than in Zapier integration itself 🤔 
- to avoid the zapier stored shash file I think the dehidration you've proposed would be a much cleaner solution
- there is no need to convert the image url back and forth - the idea is that the client should be able to operate without knowing about `__GHOSTURL__` existence
- you can hit the uploads endpoints all at once, it's not like a hundred uploads goes out all at once - it is only three of them. but don't mind leaving this optimization in place

There have not been reports about this issue ever since the initial report. I'll close it out for now and very happy to reopen and let @royalfig to give a hand if there's interest in fixing this bug.
