### ISSUE TITLE
Changing comped plan to "false" might not be working

### ISSUE THREAD

**Issue by naz** [TryGhost/Zapier#65]
The issue is based on a report sent through [Zapier issue tracker](https://developer.zapier.com/app/1566/issues/21). Needs to be confirmed first and triaged appropriately.

**Comment by naz** [comment]
@royalfig this one could be an interesting one to investigate. I'm suspecting it could be an API bug in members, but did not check they yet.

**Comment by royalfig** [comment]
I worked with Rish to update the API, as this method was failing. 

Ref: https://github.com/TryGhost/Ghost/commit/007637973ea40758da0369906d7be95e635eafaa
